///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BorrarCargoActual recording.
    /// </summary>
    [TestModule("a863763b-da19-486c-bf9c-07a1b40f752c", ModuleType.Recording, 1)]
    public partial class BorrarCargoActual : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Qualis_Bot_SalesNavigatorRepository repository.
        /// </summary>
        public static Qualis_Bot_SalesNavigatorRepository repo = Qualis_Bot_SalesNavigatorRepository.Instance;

        static BorrarCargoActual instance = new BorrarCargoActual();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BorrarCargoActual()
        {
            CantidadDeResultados = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BorrarCargoActual Instance
        {
            get { return instance; }
        }

#region Variables

        string _CantidadDeResultados;

        /// <summary>
        /// Gets or sets the value of variable CantidadDeResultados.
        /// </summary>
        [TestVariable("383bd49c-a755-4d56-8424-333c0418ed49")]
        public string CantidadDeResultados
        {
            get { return _CantidadDeResultados; }
            set { _CantidadDeResultados = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'InicioSalesNavigator.GlobalTypeaheadSearchInput' at Center.", repo.InicioSalesNavigator.GlobalTypeaheadSearchInputInfo, new RecordItemIndex(0));
            repo.InicioSalesNavigator.GlobalTypeaheadSearchInput.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Back}' with focus on 'InicioSalesNavigator.GlobalTypeaheadSearchInput'.", repo.InicioSalesNavigator.GlobalTypeaheadSearchInputInfo, new RecordItemIndex(1));
            repo.InicioSalesNavigator.GlobalTypeaheadSearchInput.PressKeys("{LControlKey down}{Akey}{LControlKey up}{Back}");
            Delay.Milliseconds(0);
            
            IfCargoActual();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
