///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickEnGuardarLista recording.
    /// </summary>
    [TestModule("fe3cad9d-aefb-4c13-8b6b-511a5158c113", ModuleType.Recording, 1)]
    public partial class ClickEnGuardarLista : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Qualis_Bot_SalesNavigatorRepository repository.
        /// </summary>
        public static Qualis_Bot_SalesNavigatorRepository repo = Qualis_Bot_SalesNavigatorRepository.Instance;

        static ClickEnGuardarLista instance = new ClickEnGuardarLista();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickEnGuardarLista()
        {
            validarPaisNombreEmpresa = "";
            nombreEmpresa = "Qualia ";
            pais = "Argentina";
            paisNombreEmpresa = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickEnGuardarLista Instance
        {
            get { return instance; }
        }

#region Variables

        string _validarPaisNombreEmpresa;

        /// <summary>
        /// Gets or sets the value of variable validarPaisNombreEmpresa.
        /// </summary>
        [TestVariable("1188c870-a406-4d71-9b1a-8540fafd5727")]
        public string validarPaisNombreEmpresa
        {
            get { return _validarPaisNombreEmpresa; }
            set { _validarPaisNombreEmpresa = value; }
        }

        string _paisNombreEmpresa;

        /// <summary>
        /// Gets or sets the value of variable paisNombreEmpresa.
        /// </summary>
        [TestVariable("95629006-f7c6-41a4-bf98-6356720204a0")]
        public string paisNombreEmpresa
        {
            get { return _paisNombreEmpresa; }
            set { _paisNombreEmpresa = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable pais.
        /// </summary>
        [TestVariable("d1c3cec8-4516-4321-86e5-c06e33270c07")]
        public string pais
        {
            get { return repo.pais; }
            set { repo.pais = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable nombreEmpresa.
        /// </summary>
        [TestVariable("243376d0-5738-43b5-a836-b6324bd9751e")]
        public string nombreEmpresa
        {
            get { return repo.nombreEmpresa; }
            set { repo.nombreEmpresa = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.GuardarEnLaLista' at Center.", repo.InicioSalesNavigator.GuardarEnLaListaInfo, new RecordItemIndex(0));
            repo.InicioSalesNavigator.GuardarEnLaLista.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "El valor de la variable pais es:", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "User", pais, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "User", "El valor de la variable nombreEmpresa", new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "User", nombreEmpresa, new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(5));
            Delay.Duration(10000, false);
            
            paisNombreEmpresa = borrarEspacios(pais, nombreEmpresa);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'InicioSalesNavigator.Copy_of_ArgentinaQualia1' and assigning its value to variable 'validarPaisNombreEmpresa'.", repo.InicioSalesNavigator.Copy_of_ArgentinaQualia1Info, new RecordItemIndex(7));
            validarPaisNombreEmpresa = repo.InicioSalesNavigator.Copy_of_ArgentinaQualia1.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Valor de la variable validarPaisNombreEmpresa+++++", new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "User", validarPaisNombreEmpresa, new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 6s.", new RecordItemIndex(10));
            Delay.Duration(6000, false);
            
            try {
                //Report.Log(ReportLevel.Info, "Get Value", "(Optional Action)\r\nGetting attribute 'InnerText' from item 'ContinueAndFail.pais_nombreEmpresa' and assigning its value to variable 'validarPaisNombreEmpresa'.", repo.ContinueAndFail.pais_nombreEmpresaInfo, new RecordItemIndex(11));
                //validarPaisNombreEmpresa = repo.ContinueAndFail.pais_nombreEmpresa.Element.GetAttributeValueText("InnerText");
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.ArgentinaQualia' at Center.", repo.InicioSalesNavigator.ArgentinaQualiaInfo, new RecordItemIndex(12));
            //repo.InicioSalesNavigator.ArgentinaQualia.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.GuardarEnLaLista' at Center.", repo.InicioSalesNavigator.GuardarEnLaListaInfo, new RecordItemIndex(13));
            //repo.InicioSalesNavigator.GuardarEnLaLista.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.ArgentinaQualia1' at Center.", repo.InicioSalesNavigator.ArgentinaQualia1Info, new RecordItemIndex(14));
            //repo.InicioSalesNavigator.ArgentinaQualia1.Click();
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
