///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CrearCantPageCSV recording.
    /// </summary>
    [TestModule("d604b842-80e2-4526-a19e-301b25ceef44", ModuleType.Recording, 1)]
    public partial class CrearCantPageCSV : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Qualis_Bot_SalesNavigatorRepository repository.
        /// </summary>
        public static Qualis_Bot_SalesNavigatorRepository repo = Qualis_Bot_SalesNavigatorRepository.Instance;

        static CrearCantPageCSV instance = new CrearCantPageCSV();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CrearCantPageCSV()
        {
            cantidadDeResultados = "63";
            nombrePersona = "";
            TodosSeleccionados = "";
            cantPage = "";
            cantidad = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CrearCantPageCSV Instance
        {
            get { return instance; }
        }

#region Variables

        string _cantidadDeResultados;

        /// <summary>
        /// Gets or sets the value of variable cantidadDeResultados.
        /// </summary>
        [TestVariable("300a0419-f37e-49c1-b6ea-59836912e235")]
        public string cantidadDeResultados
        {
            get { return _cantidadDeResultados; }
            set { _cantidadDeResultados = value; }
        }

        string _nombrePersona;

        /// <summary>
        /// Gets or sets the value of variable nombrePersona.
        /// </summary>
        [TestVariable("2e20b37d-06b8-4ed2-be3c-7bb751839e8e")]
        public string nombrePersona
        {
            get { return _nombrePersona; }
            set { _nombrePersona = value; }
        }

        string _TodosSeleccionados;

        /// <summary>
        /// Gets or sets the value of variable TodosSeleccionados.
        /// </summary>
        [TestVariable("c1a29866-b832-4a45-8a00-f8105ea19612")]
        public string TodosSeleccionados
        {
            get { return _TodosSeleccionados; }
            set { _TodosSeleccionados = value; }
        }

        string _cantPage;

        /// <summary>
        /// Gets or sets the value of variable cantPage.
        /// </summary>
        [TestVariable("e8fa0373-7c02-4442-b7d5-178b7a6c521c")]
        public string cantPage
        {
            get { return _cantPage; }
            set { _cantPage = value; }
        }

        string _cantidad;

        /// <summary>
        /// Gets or sets the value of variable cantidad.
        /// </summary>
        [TestVariable("5cd29da8-56e3-4978-8f10-4c9cde2414f2")]
        public string cantidad
        {
            get { return _cantidad; }
            set { _cantidad = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            CrearCSV();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
