///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CrearListaCliente recording.
    /// </summary>
    [TestModule("5c0d1a84-20dd-4629-b11b-57c4dbc59f95", ModuleType.Recording, 1)]
    public partial class CrearListaCliente : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Qualis_Bot_SalesNavigatorRepository repository.
        /// </summary>
        public static Qualis_Bot_SalesNavigatorRepository repo = Qualis_Bot_SalesNavigatorRepository.Instance;

        static CrearListaCliente instance = new CrearListaCliente();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CrearListaCliente()
        {
            pais = "";
            nombreEmpresa = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CrearListaCliente Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable pais.
        /// </summary>
        [TestVariable("638848e2-0b53-434e-960a-66bdd249bff0")]
        public string pais
        {
            get { return repo.pais; }
            set { repo.pais = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable nombreEmpresa.
        /// </summary>
        [TestVariable("c801a717-0096-443d-b601-edc5fd6cc760")]
        public string nombreEmpresa
        {
            get { return repo.nombreEmpresa; }
            set { repo.nombreEmpresa = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(0));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.GuardarEnLaLista' at Center.", repo.InicioSalesNavigator.GuardarEnLaListaInfo, new RecordItemIndex(1));
            repo.InicioSalesNavigator.GuardarEnLaLista.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(2));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.CrearLista' at Center.", repo.InicioSalesNavigator.CrearListaInfo, new RecordItemIndex(3));
            repo.InicioSalesNavigator.CrearLista.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.TextNombreLista' at Center.", repo.InicioSalesNavigator.TextNombreListaInfo, new RecordItemIndex(4));
            repo.InicioSalesNavigator.TextNombreLista.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$pais'.", new RecordItemIndex(5));
            Keyboard.Press(pais);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '_'.", new RecordItemIndex(6));
            Keyboard.Press("_");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$nombreEmpresa'.", new RecordItemIndex(7));
            Keyboard.Press(nombreEmpresa);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.ButtonGuardarNuevaLista' at Center.", repo.InicioSalesNavigator.ButtonGuardarNuevaListaInfo, new RecordItemIndex(8));
            repo.InicioSalesNavigator.ButtonGuardarNuevaLista.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
