///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using Microsoft.Office.Interop.Excel;

namespace Qualis_Bot_SalesNavigator
{
	public partial class EscribirEnElExcel
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void xlsWorker()
		{
			
			var excelApp = new Microsoft.Office.Interop.Excel.Application();
			
			//Abro el archivo excel
			excelApp.Workbooks.Open(@"D:\TEMP\OutputEmpresas.xlsx").Activate();
			//En caso que funcione sera esta la direccion donde se ecuentre el Excel
			//excelApp.Workbooks.Open(@"C:%userprofile%\TEMP\OutputEmpresas.xlsx").Activate();
			excelApp.Visible=false;
			
			//Selecciono el WorkSheet
			((Microsoft.Office.Interop.Excel.Worksheet)excelApp.ActiveWorkbook.Sheets["DatosObtenidos"]).Select();
			
			int fila=1;
			//string ultimaFilaEscrita=excelApp.Range["A"+fila].Value;
			
			//Tomo la ultima fila escrita en el documento Excel
			while(excelApp.Range["A"+fila].Value != null){
				fila=fila+1;
				
			}
			
			int filaAEscribir=fila;
			
			//Escribo el pais
			excelApp.Range["A"+filaAEscribir].Value = "variablePais";
			
			//Escribo la industria
			excelApp.Range["B"+filaAEscribir].Value = "variableIndustria";
			
			//Escribo el Nombre Empresa
			excelApp.Range["C"+filaAEscribir].Value = "variableNombreEmpresa";
			
			//Escribo el Nombre Completo
			excelApp.Range["D"+filaAEscribir].Value = "variableNombreCompleto";
			
			//Escribo el Rol
			excelApp.Range["E"+filaAEscribir].Value = "variablePuestoPersona";
			
			//Escribo el linkedin
			excelApp.Range["F"+filaAEscribir].Value = "variableLinkedin";
			
			//Guardo el excel y lo cierro
			//Se puede grabar de 2 formas, por si la 1ra falla
			//excelApp.Save();
			excelApp.ActiveWorkbook.Save();
			//Cierro el Excel
			excelApp.Workbooks.Close();

		}

	}
}

