///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EscribirEnExcel recording.
    /// </summary>
    [TestModule("4e58f63e-7275-4fa3-9be3-92a8a45dda15", ModuleType.Recording, 1)]
    public partial class EscribirEnElExcel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Qualis_Bot_SalesNavigatorRepository repository.
        /// </summary>
        public static Qualis_Bot_SalesNavigatorRepository repo = Qualis_Bot_SalesNavigatorRepository.Instance;

        static EscribirEnElExcel instance = new EscribirEnElExcel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EscribirEnElExcel()
        {
            Pais = "";
            Industria = "";
            NombreEmpresa = "";
            nombrePersona = "";
            puestoPersona = "";
            linkPersona = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EscribirEnElExcel Instance
        {
            get { return instance; }
        }

#region Variables

        string _nombrePersona;

        /// <summary>
        /// Gets or sets the value of variable nombrePersona.
        /// </summary>
        [TestVariable("dcdee6b7-c6ad-4420-beeb-aad3ceb1d221")]
        public string nombrePersona
        {
            get { return _nombrePersona; }
            set { _nombrePersona = value; }
        }

        string _puestoPersona;

        /// <summary>
        /// Gets or sets the value of variable puestoPersona.
        /// </summary>
        [TestVariable("65e57354-479e-400e-ad71-03a6c5d13eca")]
        public string puestoPersona
        {
            get { return _puestoPersona; }
            set { _puestoPersona = value; }
        }

        string _linkPersona;

        /// <summary>
        /// Gets or sets the value of variable linkPersona.
        /// </summary>
        [TestVariable("477d12c3-4acb-4c13-8f90-51c585365919")]
        public string linkPersona
        {
            get { return _linkPersona; }
            set { _linkPersona = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Pais.
        /// </summary>
        [TestVariable("857d3733-6607-474a-adf9-400391f97f80")]
        public string Pais
        {
            get { return repo.pais; }
            set { repo.pais = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Industria.
        /// </summary>
        [TestVariable("518afc47-8b6c-4202-b786-fda17020e1a9")]
        public string Industria
        {
            get { return repo.Industria; }
            set { repo.Industria = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NombreEmpresa.
        /// </summary>
        [TestVariable("8207d13a-36cb-4367-a045-9ac779bf3292")]
        public string NombreEmpresa
        {
            get { return repo.nombreEmpresa; }
            set { repo.nombreEmpresa = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            xlsWorker();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
