///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FiltroPorIndustria recording.
    /// </summary>
    [TestModule("8e2b7bbc-cbf7-4b9c-b2e0-e5616a7085c0", ModuleType.Recording, 1)]
    public partial class FiltroPorIndustria : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Qualis_Bot_SalesNavigatorRepository repository.
        /// </summary>
        public static Qualis_Bot_SalesNavigatorRepository repo = Qualis_Bot_SalesNavigatorRepository.Instance;

        static FiltroPorIndustria instance = new FiltroPorIndustria();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FiltroPorIndustria()
        {
            Industria = "Servicios financieros";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FiltroPorIndustria Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Industria.
        /// </summary>
        [TestVariable("5427be5d-4c75-47c5-bf70-b911ea0668bf")]
        public string Industria
        {
            get { return repo.Industria; }
            set { repo.Industria = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.Industria' at Center.", repo.InicioSalesNavigator.IndustriaInfo, new RecordItemIndex(0));
            repo.InicioSalesNavigator.Industria.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.TextIndustria' at Center.", repo.InicioSalesNavigator.TextIndustriaInfo, new RecordItemIndex(1));
            repo.InicioSalesNavigator.TextIndustria.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Industria'.", new RecordItemIndex(2));
            Keyboard.Press(Industria);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.IncluirIndustriaEnElFiltroIndustria' at Center.", repo.InicioSalesNavigator.IncluirIndustriaEnElFiltroIndustriaInfo, new RecordItemIndex(3));
            repo.InicioSalesNavigator.IncluirIndustriaEnElFiltroIndustria.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
