///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FiltroPorUbicacion recording.
    /// </summary>
    [TestModule("9dc64434-3d03-4cc1-a085-3236066587ec", ModuleType.Recording, 1)]
    public partial class FiltroPorUbicacion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Qualis_Bot_SalesNavigatorRepository repository.
        /// </summary>
        public static Qualis_Bot_SalesNavigatorRepository repo = Qualis_Bot_SalesNavigatorRepository.Instance;

        static FiltroPorUbicacion instance = new FiltroPorUbicacion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FiltroPorUbicacion()
        {
            Pais = "Argentina";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FiltroPorUbicacion Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Pais.
        /// </summary>
        [TestVariable("88fba158-8c8a-49e5-bddf-f1d3cad38c3e")]
        public string Pais
        {
            get { return repo.pais; }
            set { repo.pais = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.Ubicacion' at Center.", repo.InicioSalesNavigator.UbicacionInfo, new RecordItemIndex(0));
            repo.InicioSalesNavigator.Ubicacion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.TextUbicacion' at Center.", repo.InicioSalesNavigator.TextUbicacionInfo, new RecordItemIndex(1));
            repo.InicioSalesNavigator.TextUbicacion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Pais'.", new RecordItemIndex(2));
            Keyboard.Press(Pais);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.IncluirArgentinaEnElFiltroRegion' at Center.", repo.InicioSalesNavigator.IncluirArgentinaEnElFiltroRegionInfo, new RecordItemIndex(3));
            repo.InicioSalesNavigator.IncluirArgentinaEnElFiltroRegion.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
