///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The IrATodosLosEmpleados recording.
    /// </summary>
    [TestModule("ad68b60c-8516-4ac6-9ac3-df35a24ef674", ModuleType.Recording, 1)]
    public partial class IrATodosLosEmpleados : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Qualis_Bot_SalesNavigatorRepository repository.
        /// </summary>
        public static Qualis_Bot_SalesNavigatorRepository repo = Qualis_Bot_SalesNavigatorRepository.Instance;

        static IrATodosLosEmpleados instance = new IrATodosLosEmpleados();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IrATodosLosEmpleados()
        {
            nombreEmpresa = "Galicia Seguros  ";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IrATodosLosEmpleados Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable nombreEmpresa.
        /// </summary>
        [TestVariable("90b20609-d613-424b-9c4f-132b2c390d55")]
        public string nombreEmpresa
        {
            get { return repo.nombreEmpresa; }
            set { repo.nombreEmpresa = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'InicioSalesNavigator.ValidacionNombreEmpresaIndustria'.", repo.InicioSalesNavigator.ValidacionNombreEmpresaIndustriaInfo, new RecordItemIndex(0));
            repo.InicioSalesNavigator.ValidacionNombreEmpresaIndustria.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'InicioSalesNavigator.TodosLosEmpleados'", repo.InicioSalesNavigator.TodosLosEmpleadosInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.InicioSalesNavigator.TodosLosEmpleadosInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.TodosLosEmpleados' at Center.", repo.InicioSalesNavigator.TodosLosEmpleadosInfo, new RecordItemIndex(2));
            repo.InicioSalesNavigator.TodosLosEmpleados.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
