///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Qualis_Bot_SalesNavigatorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("881b03a7-de86-41df-bc6e-b74240262674")]
    public partial class Qualis_Bot_SalesNavigatorRepository : RepoGenBaseFolder
    {
        static Qualis_Bot_SalesNavigatorRepository instance = new Qualis_Bot_SalesNavigatorRepository();
        Qualis_Bot_SalesNavigatorRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Qualis_Bot_SalesNavigatorRepositoryFolders.InicioSalesNavigatorAppFolder _iniciosalesnavigator;
        Qualis_Bot_SalesNavigatorRepositoryFolders.ContinueAndFailAppFolder _continueandfail;
        Qualis_Bot_SalesNavigatorRepositoryFolders.OutputEmpresasXlsxExcelAppFolder _outputempresasxlsxexcel;
        Qualis_Bot_SalesNavigatorRepositoryFolders.ChromeAppFolder _chrome;
        Qualis_Bot_SalesNavigatorRepositoryFolders.ContAndFail_ChromeAppFolder _contandfail_chrome;
        Qualis_Bot_SalesNavigatorRepositoryFolders.InicioAppFolder _inicio;

        /// <summary>
        /// Gets the singleton class instance representing the Qualis_Bot_SalesNavigatorRepository element repository.
        /// </summary>
        [RepositoryFolder("881b03a7-de86-41df-bc6e-b74240262674")]
        public static Qualis_Bot_SalesNavigatorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Qualis_Bot_SalesNavigatorRepository() 
            : base("Qualis_Bot_SalesNavigatorRepository", "/", null, 0, false, "881b03a7-de86-41df-bc6e-b74240262674", ".\\RepositoryImages\\Qualis_Bot_SalesNavigatorRepository881b03a7.rximgres")
        {
            _applicationundertest = new Qualis_Bot_SalesNavigatorRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _iniciosalesnavigator = new Qualis_Bot_SalesNavigatorRepositoryFolders.InicioSalesNavigatorAppFolder(this);
            _continueandfail = new Qualis_Bot_SalesNavigatorRepositoryFolders.ContinueAndFailAppFolder(this);
            _outputempresasxlsxexcel = new Qualis_Bot_SalesNavigatorRepositoryFolders.OutputEmpresasXlsxExcelAppFolder(this);
            _chrome = new Qualis_Bot_SalesNavigatorRepositoryFolders.ChromeAppFolder(this);
            _contandfail_chrome = new Qualis_Bot_SalesNavigatorRepositoryFolders.ContAndFail_ChromeAppFolder(this);
            _inicio = new Qualis_Bot_SalesNavigatorRepositoryFolders.InicioAppFolder(this);
        }

#region Variables

        string _pais = "Argentina";

        /// <summary>
        /// Gets or sets the value of variable pais.
        /// </summary>
        [TestVariable("d1c3cec8-4516-4321-86e5-c06e33270c07")]
        public string pais
        {
            get { return _pais; }
            set { _pais = value; }
        }

        string _Industria = "Servicios financieros";

        /// <summary>
        /// Gets or sets the value of variable Industria.
        /// </summary>
        [TestVariable("48ee2248-30c5-4ed5-82d6-ec3f16680e3a")]
        public string Industria
        {
            get { return _Industria; }
            set { _Industria = value; }
        }

        string _nombreEmpresa = "Galicia Seguros  ";

        /// <summary>
        /// Gets or sets the value of variable nombreEmpresa.
        /// </summary>
        [TestVariable("243376d0-5738-43b5-a836-b6324bd9751e")]
        public string nombreEmpresa
        {
            get { return _nombreEmpresa; }
            set { _nombreEmpresa = value; }
        }

        string _indice = "";

        /// <summary>
        /// Gets or sets the value of variable indice.
        /// </summary>
        [TestVariable("d4f5b272-4496-4d01-b033-67a287531d6d")]
        public string indice
        {
            get { return _indice; }
            set { _indice = value; }
        }

        string _Keyword = "";

        /// <summary>
        /// Gets or sets the value of variable Keyword.
        /// </summary>
        [TestVariable("4602fb31-5ce2-40b7-97a8-9f9049747d36")]
        public string Keyword
        {
            get { return _Keyword; }
            set { _Keyword = value; }
        }

        string _idex = "";

        /// <summary>
        /// Gets or sets the value of variable idex.
        /// </summary>
        [TestVariable("ee8f227b-3f9b-475e-9337-ef7375b389a6")]
        public string idex
        {
            get { return _idex; }
            set { _idex = value; }
        }

        string _index = "1";

        /// <summary>
        /// Gets or sets the value of variable index.
        /// </summary>
        [TestVariable("2fe17e89-d564-43eb-832f-8b412e95c8ef")]
        public string index
        {
            get { return _index; }
            set { _index = value; }
        }

        string _empresa = "";

        /// <summary>
        /// Gets or sets the value of variable empresa.
        /// </summary>
        [TestVariable("c85d4633-f7db-49b5-83a4-49c44d423d24")]
        public string empresa
        {
            get { return _empresa; }
            set { _empresa = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("881b03a7-de86-41df-bc6e-b74240262674")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("d8482183-938a-4f65-adf9-1f1438f09dc8")]
        public virtual Qualis_Bot_SalesNavigatorRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The InicioSalesNavigator folder.
        /// </summary>
        [RepositoryFolder("69f8ea21-5306-4680-8cf8-dd622b013713")]
        public virtual Qualis_Bot_SalesNavigatorRepositoryFolders.InicioSalesNavigatorAppFolder InicioSalesNavigator
        {
            get { return _iniciosalesnavigator; }
        }

        /// <summary>
        /// The ContinueAndFail folder.
        /// </summary>
        [RepositoryFolder("51ba4c9c-11a8-48ba-b3df-b0f8bcc2ce30")]
        public virtual Qualis_Bot_SalesNavigatorRepositoryFolders.ContinueAndFailAppFolder ContinueAndFail
        {
            get { return _continueandfail; }
        }

        /// <summary>
        /// The OutputEmpresasXlsxExcel folder.
        /// </summary>
        [RepositoryFolder("041cc2f3-9051-467d-80af-d1124ff1688d")]
        public virtual Qualis_Bot_SalesNavigatorRepositoryFolders.OutputEmpresasXlsxExcelAppFolder OutputEmpresasXlsxExcel
        {
            get { return _outputempresasxlsxexcel; }
        }

        /// <summary>
        /// The Chrome folder.
        /// </summary>
        [RepositoryFolder("6f3b421b-86e1-4ef2-bbc7-d7ddfe587996")]
        public virtual Qualis_Bot_SalesNavigatorRepositoryFolders.ChromeAppFolder Chrome
        {
            get { return _chrome; }
        }

        /// <summary>
        /// The ContAndFail_Chrome folder.
        /// </summary>
        [RepositoryFolder("29d6aa49-1a0a-40e2-9254-b03910dce2bf")]
        public virtual Qualis_Bot_SalesNavigatorRepositoryFolders.ContAndFail_ChromeAppFolder ContAndFail_Chrome
        {
            get { return _contandfail_chrome; }
        }

        /// <summary>
        /// The Inicio folder.
        /// </summary>
        [RepositoryFolder("d8d97ac7-149e-4d30-aced-65122ba5e54c")]
        public virtual Qualis_Bot_SalesNavigatorRepositoryFolders.InicioAppFolder Inicio
        {
            get { return _inicio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Qualis_Bot_SalesNavigatorRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("d8482183-938a-4f65-adf9-1f1438f09dc8")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain>'https://www.linkedin.com/sales']", parentFolder, 30000, null, false, "d8482183-938a-4f65-adf9-1f1438f09dc8", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d8482183-938a-4f65-adf9-1f1438f09dc8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d8482183-938a-4f65-adf9-1f1438f09dc8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The InicioSalesNavigatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("69f8ea21-5306-4680-8cf8-dd622b013713")]
        public partial class InicioSalesNavigatorAppFolder : RepoGenBaseFolder
        {
            Qualis_Bot_SalesNavigatorRepositoryFolders.DatosAObtenerFolder _datosaobtener;
            RepoItemInfo _globaltypeaheadsearchinputInfo;
            RepoItemInfo _ubicacionInfo;
            RepoItemInfo _industriaInfo;
            RepoItemInfo _textubicacionInfo;
            RepoItemInfo _textindustriaInfo;
            RepoItemInfo _incluirargentinaenelfiltroregionInfo;
            RepoItemInfo _incluirindustriaenelfiltroindustriaInfo;
            RepoItemInfo _validacionnombreempresaindustriaInfo;
            RepoItemInfo _imgvalidacionnombreempresaindustriaInfo;
            RepoItemInfo _responsablesdelasdecisiones855Info;
            RepoItemInfo _spantag3resultadosInfo;
            RepoItemInfo _lisegunindiceInfo;
            RepoItemInfo _copy_of_lisegunindiceInfo;
            RepoItemInfo _nombreliInfo;
            RepoItemInfo _cuentasInfo;
            RepoItemInfo _lilistInfo;
            RepoItemInfo _guardarenlalistaInfo;
            RepoItemInfo _bolbancaInfo;
            RepoItemInfo _artdecodropdowncontentartdecodropdoInfo;
            RepoItemInfo _agregarnuevalistaInfo;
            RepoItemInfo _selecciondetodoslosperfilesInfo;
            RepoItemInfo _chekyaestanseleccionadosInfo;
            RepoItemInfo _btn_cargoactualInfo;
            RepoItemInfo _input_anadircargoactualInfo;
            RepoItemInfo _copy_of_globaltypeaheadsearchinput1Info;
            RepoItemInfo _copy_of_globaltypeaheadsearchinputInfo;
            RepoItemInfo _textnombrelistaInfo;
            RepoItemInfo _buttonguardarnuevalistaInfo;
            RepoItemInfo _btn_borrarcargoactualInfo;
            RepoItemInfo _li_cargoactual_opcion1Info;
            RepoItemInfo _crearlistaInfo;
            RepoItemInfo _argentinaqualiaInfo;
            RepoItemInfo _flexfullwidthjustifyspacebetweenInfo;
            RepoItemInfo _argentinaqualia1Info;
            RepoItemInfo _copy_of_argentinaqualia1Info;
            RepoItemInfo _matiasgimenezInfo;
            RepoItemInfo _todoslosempleadosInfo;
            RepoItemInfo _gerentedeecosistemayfidelidadInfo;
            RepoItemInfo _somesvgtagInfo;
            RepoItemInfo _verperfildelinkedinInfo;
            RepoItemInfo _spantagiconps32ckInfo;

            /// <summary>
            /// Creates a new InicioSalesNavigator  folder.
            /// </summary>
            public InicioSalesNavigatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("InicioSalesNavigator", "/dom[@domain='www.linkedin.com']", parentFolder, 30000, null, false, "69f8ea21-5306-4680-8cf8-dd622b013713", "")
            {
                _datosaobtener = new Qualis_Bot_SalesNavigatorRepositoryFolders.DatosAObtenerFolder(this);
                _globaltypeaheadsearchinputInfo = new RepoItemInfo(this, "GlobalTypeaheadSearchInput", ".//input[#'global-typeahead-search-input']", "", 30000, null, "89f6dd15-8a14-4946-9797-ff1dc94873d1");
                _ubicacionInfo = new RepoItemInfo(this, "Ubicacion", ".//main[#'content-main']//fieldset[@title>'Ubicación']/div/button/tag[@tagname='li-icon']/svg", "", 30000, null, "e73b391f-40bc-4e7a-bcb8-378d9bd6403f");
                _industriaInfo = new RepoItemInfo(this, "Industria", ".//fieldset[@title='Industria']//button[@visible='True']", "", 30000, null, "d50c92b4-f8dd-476b-a458-01b76fe1a522");
                _textubicacionInfo = new RepoItemInfo(this, "TextUbicacion", ".//fieldset[@title>'Ubicación']//input[@type='text']", "", 30000, null, "c2114fad-5113-4b39-b644-20a726ac75aa");
                _textindustriaInfo = new RepoItemInfo(this, "TextIndustria", ".//fieldset[@title='Industria']//input[@type='text']", "", 30000, null, "34055f46-5d04-4986-82c4-624659e166db");
                _incluirargentinaenelfiltroregionInfo = new RepoItemInfo(this, "IncluirArgentinaEnElFiltroRegion", ".//main[#'content-main']//div[@title>'Incluir «'+$pais+'» en el']", "", 30000, null, "803b4053-a5a5-4bcc-b31b-254456958d89");
                _incluirindustriaenelfiltroindustriaInfo = new RepoItemInfo(this, "IncluirIndustriaEnElFiltroIndustria", ".//fieldset[@title='Industria']//button[@title>'Incluir «'+$Industria]", "", 30000, null, "4f9c02c7-5506-4d20-b97d-20e22fed6e79");
                _validacionnombreempresaindustriaInfo = new RepoItemInfo(this, "ValidacionNombreEmpresaIndustria", ".//div[#'search-results-container']//a[@innertext=$nombreEmpresa]", "", 30000, null, "7af6cc06-909f-4092-a6ab-3019e5ed10c5");
                _imgvalidacionnombreempresaindustriaInfo = new RepoItemInfo(this, "ImgValidacionNombreEmpresaIndustria", ".//div[#'search-results-container']//span[@innertext=$Industria]/../../..//a[@innertext=$nombreEmpresa]/../../../..", "", 30000, null, "359c8191-b33a-4913-a502-d135cb214de2");
                _responsablesdelasdecisiones855Info = new RepoItemInfo(this, "ResponsablesDeLasDecisiones855", ".//div[#'account']//a[@innertext>'Responsables de las decisiones' and @visible='True']", "", 30000, null, "c1fe81fd-02c1-459a-a7da-6e3054d73c32");
                _spantag3resultadosInfo = new RepoItemInfo(this, "SpanTag3Resultados", ".//main[#'content-main']//span[@innertext<'resultados']", "", 30000, null, "ef64d75d-1836-47ac-b804-9f631baafa78");
                _lisegunindiceInfo = new RepoItemInfo(this, "LiSegunIndice", ".//div[#'search-results-container']//li[$indice]", "", 30000, null, "69632222-0980-4aea-8289-19f8a7f32025");
                _copy_of_lisegunindiceInfo = new RepoItemInfo(this, "Copy_of_LiSegunIndice", ".//div[#'search-results-container']//li[$indice]", "", 30000, null, "363c7c67-b659-4869-998b-32efb5966640");
                _nombreliInfo = new RepoItemInfo(this, "nombreLi", ".//div[#'search-results-container']//ol/li[$indice]//a[@data-anonymize='person-name']", "", 30000, null, "d7922987-6fcf-4b01-8087-09216e57c7c7");
                _cuentasInfo = new RepoItemInfo(this, "Cuentas", ".//main[#'content-main']//a[@innertext='Cuentas']", "", 30000, null, "05ce7102-3234-42f3-9526-c74cf1e82dfe");
                _lilistInfo = new RepoItemInfo(this, "LiList", ".//div[#'search-results-container']/?/?/ol", "", 30000, null, "930cfc8c-4e0f-46c7-bcd4-b057259a71c4");
                _guardarenlalistaInfo = new RepoItemInfo(this, "GuardarEnLaLista", ".//main[#'content-main']//span[@innertext='Guardar en la lista']", "", 30000, null, "dfdcf770-387c-4886-9df4-86689d19ddf5");
                _bolbancaInfo = new RepoItemInfo(this, "BOLBanca", ".//main[#'content-main']//div[@innertext='BOL - Banca']", "", 30000, null, "11c92ad5-d8d2-46cb-bf77-b937e9bc7c75");
                _artdecodropdowncontentartdecodropdoInfo = new RepoItemInfo(this, "ArtdecoDropdownContentArtdecoDropdo", ".//main[#'content-main']/div[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div", "", 30000, null, "be9f1935-b9cf-4f8a-ad36-6633d220bdcf");
                _agregarnuevalistaInfo = new RepoItemInfo(this, "AgregarNuevaLista", ".//div//span[@innertext='Crear Lista']", "", 30000, null, "8b4ae743-141f-4d07-886d-6623c04d37a1");
                _selecciondetodoslosperfilesInfo = new RepoItemInfo(this, "SeleccionDeTodosLosPerfiles", ".//main[#'content-main']/div//span[@innertext~'eleccion']", "", 30000, null, "95bb1200-13c5-4cb2-aaed-4d73e1c95142");
                _chekyaestanseleccionadosInfo = new RepoItemInfo(this, "ChekYaEstanSeleccionados", ".//main[#'content-main']//div//span[@innertext~'eleccion']/../..//input[@type='checkbox']", "", 30000, null, "f720249c-a563-4b89-beb9-5b2c64c20bfc");
                _btn_cargoactualInfo = new RepoItemInfo(this, "Btn_CargoActual", ".//main[#'content-main']//fieldset[@title='Cargo actual']//span[@innertext='Cargo actual']/../../button", "", 30000, null, "7e6e8108-9048-496c-8889-1009268bd6be");
                _input_anadircargoactualInfo = new RepoItemInfo(this, "Input_AnadirCargoActual", ".//main[#'content-main']//input[@type='text' and @placeholder='Añadir cargos actuales']", "", 30000, null, "bb18b76d-3ffd-43d3-b675-fec7803ed6cb");
                _copy_of_globaltypeaheadsearchinput1Info = new RepoItemInfo(this, "Copy_of_GlobalTypeaheadSearchInput1", ".//input[#'global-typeahead-search-input']", "", 30000, null, "f90bfafc-929a-4567-aa0c-fd68dd2cfc64");
                _copy_of_globaltypeaheadsearchinputInfo = new RepoItemInfo(this, "Copy_of_GlobalTypeaheadSearchInput", ".//input[#'global-typeahead-search-input']", "", 30000, null, "04616272-ff41-4e42-9b40-5b42b2819562");
                _textnombrelistaInfo = new RepoItemInfo(this, "TextNombreLista", ".//div[#'artdeco-modal-outlet']//input[@type='text']", "", 30000, null, "6b4a2d9f-d0a6-4e04-ac27-f396ae4c01a8");
                _buttonguardarnuevalistaInfo = new RepoItemInfo(this, "ButtonGuardarNuevaLista", ".//div[#'artdeco-modal-outlet']/div/div/div[3]/button[2]", "", 30000, null, "8a747756-4f25-497a-934a-38b5c76b1ff4");
                _btn_borrarcargoactualInfo = new RepoItemInfo(this, "Btn_BorrarCargoActual", ".//main[#'content-main']//fieldset[@title='Cargo actual']//div[@title=$Keyword]//button[@title>'Eliminar filtro Cargo actual:']", "element", 30000, null, "91443328-96d9-47a7-a0c2-c6da21b53035");
                _li_cargoactual_opcion1Info = new RepoItemInfo(this, "Li_CargoActual_Opcion1", ".//main[#'content-main']//fieldset[@title='Cargo actual']//ul/li[1][@visible='True']", "", 30000, null, "05f58acb-c028-4c77-b0fe-2ff2a9f95b84");
                _crearlistaInfo = new RepoItemInfo(this, "CrearLista", ".//div[#'hue-web-menu-outlet']//span[@innertext='Crear lista']", "", 30000, null, "d9b67c36-5249-45cf-94b2-bc41d234616a");
                _argentinaqualiaInfo = new RepoItemInfo(this, "ArgentinaQualia", ".//h2[@innertext='Añadir a la lista']/.//span[@innertext=$pais+'_'+$nombreEmpresa]", "", 30000, null, "7e5c9992-1267-4564-8afb-cccc3ac60f09");
                _flexfullwidthjustifyspacebetweenInfo = new RepoItemInfo(this, "FlexFullWidthJustifySpaceBetween", ".//div[#'search-results-container']/?/?/ol/li[2]/div/div/div[2]", "", 30000, null, "d53d1b7a-b983-4a65-bf43-c7b1540d784c");
                _argentinaqualia1Info = new RepoItemInfo(this, "ArgentinaQualia1", ".//div[#'hue-web-menu-outlet']//span[@innertext=$pais+'_'+$nombreEmpresa]", "", 30000, null, "b6ace614-db43-4ff4-bb98-c5b40b1baed5");
                _copy_of_argentinaqualia1Info = new RepoItemInfo(this, "Copy_of_ArgentinaQualia1", ".//span[@innertext<$pais+'_'+$nombreEmpresa]", "", 30000, null, "f20eb293-2228-4674-963e-3e39c52f02cd");
                _matiasgimenezInfo = new RepoItemInfo(this, "MatiasGimenez", ".//div[#'voyager-feed']//main/div[3]/div/div[1]/div[1]/div/div[2]/div/div/div/div[4]/div/div/a[1]/span[1]/span[1]/span[1]/span[@innertext='Matías Giménez']", "", 30000, null, "0725dc7b-dd0e-47d1-a0b6-54127ec41558");
                _todoslosempleadosInfo = new RepoItemInfo(this, "TodosLosEmpleados", ".//div[#'account']//a[@innertext>'Todos los empleados']", "", 30000, null, "1fad1f5d-e03e-4455-b75a-15da589af9f6");
                _gerentedeecosistemayfidelidadInfo = new RepoItemInfo(this, "GerenteDeEcosistemaYFidelidad", ".//div[#'search-results-container']//span[@innertext>'Gerente de Ecosistema y F']", "", 30000, null, "5c1e7c6d-bb1a-448d-b4d7-458a3bcd7135");
                _somesvgtagInfo = new RepoItemInfo(this, "SomeSvgTag", ".//section[#'profile-card-section']/section[1]/div[2]/section/div[2]/button/span[1]/svg", "", 30000, null, "5f93e09e-66b3-4be6-a6e6-1d51e4762777");
                _verperfildelinkedinInfo = new RepoItemInfo(this, "VerPerfilDeLinkedIn", ".//div[#'hue-web-menu-outlet']//div[@innertext='Ver perfil de LinkedIn']", "", 30000, null, "c0d27101-5bf5-4ac9-aab5-192a6a64cc0f");
                _spantagiconps32ckInfo = new RepoItemInfo(this, "SpanTagIconPs32ck", ".//section[#'profile-card-section']/section[1]/div[2]/section/div[2]/button/span[1]", "", 30000, null, "6d462923-60f8-44f2-a0d1-a6c1e7e8da60");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("69f8ea21-5306-4680-8cf8-dd622b013713")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("69f8ea21-5306-4680-8cf8-dd622b013713")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GlobalTypeaheadSearchInput item.
            /// </summary>
            [RepositoryItem("89f6dd15-8a14-4946-9797-ff1dc94873d1")]
            public virtual Ranorex.InputTag GlobalTypeaheadSearchInput
            {
                get
                {
                    return _globaltypeaheadsearchinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GlobalTypeaheadSearchInput item info.
            /// </summary>
            [RepositoryItemInfo("89f6dd15-8a14-4946-9797-ff1dc94873d1")]
            public virtual RepoItemInfo GlobalTypeaheadSearchInputInfo
            {
                get
                {
                    return _globaltypeaheadsearchinputInfo;
                }
            }

            /// <summary>
            /// The Ubicacion item.
            /// </summary>
            [RepositoryItem("e73b391f-40bc-4e7a-bcb8-378d9bd6403f")]
            public virtual Ranorex.SvgTag Ubicacion
            {
                get
                {
                    return _ubicacionInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The Ubicacion item info.
            /// </summary>
            [RepositoryItemInfo("e73b391f-40bc-4e7a-bcb8-378d9bd6403f")]
            public virtual RepoItemInfo UbicacionInfo
            {
                get
                {
                    return _ubicacionInfo;
                }
            }

            /// <summary>
            /// The Industria item.
            /// </summary>
            [RepositoryItem("d50c92b4-f8dd-476b-a458-01b76fe1a522")]
            public virtual Ranorex.ButtonTag Industria
            {
                get
                {
                    return _industriaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Industria item info.
            /// </summary>
            [RepositoryItemInfo("d50c92b4-f8dd-476b-a458-01b76fe1a522")]
            public virtual RepoItemInfo IndustriaInfo
            {
                get
                {
                    return _industriaInfo;
                }
            }

            /// <summary>
            /// The TextUbicacion item.
            /// </summary>
            [RepositoryItem("c2114fad-5113-4b39-b644-20a726ac75aa")]
            public virtual Ranorex.InputTag TextUbicacion
            {
                get
                {
                    return _textubicacionInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TextUbicacion item info.
            /// </summary>
            [RepositoryItemInfo("c2114fad-5113-4b39-b644-20a726ac75aa")]
            public virtual RepoItemInfo TextUbicacionInfo
            {
                get
                {
                    return _textubicacionInfo;
                }
            }

            /// <summary>
            /// The TextIndustria item.
            /// </summary>
            [RepositoryItem("34055f46-5d04-4986-82c4-624659e166db")]
            public virtual Ranorex.InputTag TextIndustria
            {
                get
                {
                    return _textindustriaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TextIndustria item info.
            /// </summary>
            [RepositoryItemInfo("34055f46-5d04-4986-82c4-624659e166db")]
            public virtual RepoItemInfo TextIndustriaInfo
            {
                get
                {
                    return _textindustriaInfo;
                }
            }

            /// <summary>
            /// The IncluirArgentinaEnElFiltroRegion item.
            /// </summary>
            [RepositoryItem("803b4053-a5a5-4bcc-b31b-254456958d89")]
            public virtual Ranorex.DivTag IncluirArgentinaEnElFiltroRegion
            {
                get
                {
                    return _incluirargentinaenelfiltroregionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The IncluirArgentinaEnElFiltroRegion item info.
            /// </summary>
            [RepositoryItemInfo("803b4053-a5a5-4bcc-b31b-254456958d89")]
            public virtual RepoItemInfo IncluirArgentinaEnElFiltroRegionInfo
            {
                get
                {
                    return _incluirargentinaenelfiltroregionInfo;
                }
            }

            /// <summary>
            /// The IncluirIndustriaEnElFiltroIndustria item.
            /// </summary>
            [RepositoryItem("4f9c02c7-5506-4d20-b97d-20e22fed6e79")]
            public virtual Ranorex.ButtonTag IncluirIndustriaEnElFiltroIndustria
            {
                get
                {
                    return _incluirindustriaenelfiltroindustriaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The IncluirIndustriaEnElFiltroIndustria item info.
            /// </summary>
            [RepositoryItemInfo("4f9c02c7-5506-4d20-b97d-20e22fed6e79")]
            public virtual RepoItemInfo IncluirIndustriaEnElFiltroIndustriaInfo
            {
                get
                {
                    return _incluirindustriaenelfiltroindustriaInfo;
                }
            }

            /// <summary>
            /// The ValidacionNombreEmpresaIndustria item.
            /// </summary>
            [RepositoryItem("7af6cc06-909f-4092-a6ab-3019e5ed10c5")]
            public virtual Ranorex.ATag ValidacionNombreEmpresaIndustria
            {
                get
                {
                    return _validacionnombreempresaindustriaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ValidacionNombreEmpresaIndustria item info.
            /// </summary>
            [RepositoryItemInfo("7af6cc06-909f-4092-a6ab-3019e5ed10c5")]
            public virtual RepoItemInfo ValidacionNombreEmpresaIndustriaInfo
            {
                get
                {
                    return _validacionnombreempresaindustriaInfo;
                }
            }

            /// <summary>
            /// The ImgValidacionNombreEmpresaIndustria item.
            /// </summary>
            [RepositoryItem("359c8191-b33a-4913-a502-d135cb214de2")]
            public virtual Ranorex.Unknown ImgValidacionNombreEmpresaIndustria
            {
                get
                {
                    return _imgvalidacionnombreempresaindustriaInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ImgValidacionNombreEmpresaIndustria item info.
            /// </summary>
            [RepositoryItemInfo("359c8191-b33a-4913-a502-d135cb214de2")]
            public virtual RepoItemInfo ImgValidacionNombreEmpresaIndustriaInfo
            {
                get
                {
                    return _imgvalidacionnombreempresaindustriaInfo;
                }
            }

            /// <summary>
            /// The ResponsablesDeLasDecisiones855 item.
            /// </summary>
            [RepositoryItem("c1fe81fd-02c1-459a-a7da-6e3054d73c32")]
            public virtual Ranorex.ATag ResponsablesDeLasDecisiones855
            {
                get
                {
                    return _responsablesdelasdecisiones855Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ResponsablesDeLasDecisiones855 item info.
            /// </summary>
            [RepositoryItemInfo("c1fe81fd-02c1-459a-a7da-6e3054d73c32")]
            public virtual RepoItemInfo ResponsablesDeLasDecisiones855Info
            {
                get
                {
                    return _responsablesdelasdecisiones855Info;
                }
            }

            /// <summary>
            /// The SpanTag3Resultados item.
            /// </summary>
            [RepositoryItem("ef64d75d-1836-47ac-b804-9f631baafa78")]
            public virtual Ranorex.SpanTag SpanTag3Resultados
            {
                get
                {
                    return _spantag3resultadosInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag3Resultados item info.
            /// </summary>
            [RepositoryItemInfo("ef64d75d-1836-47ac-b804-9f631baafa78")]
            public virtual RepoItemInfo SpanTag3ResultadosInfo
            {
                get
                {
                    return _spantag3resultadosInfo;
                }
            }

            /// <summary>
            /// The LiSegunIndice item.
            /// </summary>
            [RepositoryItem("69632222-0980-4aea-8289-19f8a7f32025")]
            public virtual Ranorex.LiTag LiSegunIndice
            {
                get
                {
                    return _lisegunindiceInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiSegunIndice item info.
            /// </summary>
            [RepositoryItemInfo("69632222-0980-4aea-8289-19f8a7f32025")]
            public virtual RepoItemInfo LiSegunIndiceInfo
            {
                get
                {
                    return _lisegunindiceInfo;
                }
            }

            /// <summary>
            /// The Copy_of_LiSegunIndice item.
            /// </summary>
            [RepositoryItem("363c7c67-b659-4869-998b-32efb5966640")]
            public virtual Ranorex.LiTag Copy_of_LiSegunIndice
            {
                get
                {
                    return _copy_of_lisegunindiceInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_LiSegunIndice item info.
            /// </summary>
            [RepositoryItemInfo("363c7c67-b659-4869-998b-32efb5966640")]
            public virtual RepoItemInfo Copy_of_LiSegunIndiceInfo
            {
                get
                {
                    return _copy_of_lisegunindiceInfo;
                }
            }

            /// <summary>
            /// The nombreLi item.
            /// </summary>
            [RepositoryItem("d7922987-6fcf-4b01-8087-09216e57c7c7")]
            public virtual Ranorex.ATag nombreLi
            {
                get
                {
                    return _nombreliInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The nombreLi item info.
            /// </summary>
            [RepositoryItemInfo("d7922987-6fcf-4b01-8087-09216e57c7c7")]
            public virtual RepoItemInfo nombreLiInfo
            {
                get
                {
                    return _nombreliInfo;
                }
            }

            /// <summary>
            /// The Cuentas item.
            /// </summary>
            [RepositoryItem("05ce7102-3234-42f3-9526-c74cf1e82dfe")]
            public virtual Ranorex.ATag Cuentas
            {
                get
                {
                    return _cuentasInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Cuentas item info.
            /// </summary>
            [RepositoryItemInfo("05ce7102-3234-42f3-9526-c74cf1e82dfe")]
            public virtual RepoItemInfo CuentasInfo
            {
                get
                {
                    return _cuentasInfo;
                }
            }

            /// <summary>
            /// The LiList item.
            /// </summary>
            [RepositoryItem("930cfc8c-4e0f-46c7-bcd4-b057259a71c4")]
            public virtual Ranorex.OlTag LiList
            {
                get
                {
                    return _lilistInfo.CreateAdapter<Ranorex.OlTag>(true);
                }
            }

            /// <summary>
            /// The LiList item info.
            /// </summary>
            [RepositoryItemInfo("930cfc8c-4e0f-46c7-bcd4-b057259a71c4")]
            public virtual RepoItemInfo LiListInfo
            {
                get
                {
                    return _lilistInfo;
                }
            }

            /// <summary>
            /// The GuardarEnLaLista item.
            /// </summary>
            [RepositoryItem("dfdcf770-387c-4886-9df4-86689d19ddf5")]
            public virtual Ranorex.SpanTag GuardarEnLaLista
            {
                get
                {
                    return _guardarenlalistaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GuardarEnLaLista item info.
            /// </summary>
            [RepositoryItemInfo("dfdcf770-387c-4886-9df4-86689d19ddf5")]
            public virtual RepoItemInfo GuardarEnLaListaInfo
            {
                get
                {
                    return _guardarenlalistaInfo;
                }
            }

            /// <summary>
            /// The BOLBanca item.
            /// </summary>
            [RepositoryItem("11c92ad5-d8d2-46cb-bf77-b937e9bc7c75")]
            public virtual Ranorex.DivTag BOLBanca
            {
                get
                {
                    return _bolbancaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BOLBanca item info.
            /// </summary>
            [RepositoryItemInfo("11c92ad5-d8d2-46cb-bf77-b937e9bc7c75")]
            public virtual RepoItemInfo BOLBancaInfo
            {
                get
                {
                    return _bolbancaInfo;
                }
            }

            /// <summary>
            /// The ArtdecoDropdownContentArtdecoDropdo item.
            /// </summary>
            [RepositoryItem("be9f1935-b9cf-4f8a-ad36-6633d220bdcf")]
            public virtual Ranorex.DivTag ArtdecoDropdownContentArtdecoDropdo
            {
                get
                {
                    return _artdecodropdowncontentartdecodropdoInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ArtdecoDropdownContentArtdecoDropdo item info.
            /// </summary>
            [RepositoryItemInfo("be9f1935-b9cf-4f8a-ad36-6633d220bdcf")]
            public virtual RepoItemInfo ArtdecoDropdownContentArtdecoDropdoInfo
            {
                get
                {
                    return _artdecodropdowncontentartdecodropdoInfo;
                }
            }

            /// <summary>
            /// The AgregarNuevaLista item.
            /// </summary>
            [RepositoryItem("8b4ae743-141f-4d07-886d-6623c04d37a1")]
            public virtual Ranorex.SpanTag AgregarNuevaLista
            {
                get
                {
                    return _agregarnuevalistaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AgregarNuevaLista item info.
            /// </summary>
            [RepositoryItemInfo("8b4ae743-141f-4d07-886d-6623c04d37a1")]
            public virtual RepoItemInfo AgregarNuevaListaInfo
            {
                get
                {
                    return _agregarnuevalistaInfo;
                }
            }

            /// <summary>
            /// The SeleccionDeTodosLosPerfiles item.
            /// </summary>
            [RepositoryItem("95bb1200-13c5-4cb2-aaed-4d73e1c95142")]
            public virtual Ranorex.SpanTag SeleccionDeTodosLosPerfiles
            {
                get
                {
                    return _selecciondetodoslosperfilesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SeleccionDeTodosLosPerfiles item info.
            /// </summary>
            [RepositoryItemInfo("95bb1200-13c5-4cb2-aaed-4d73e1c95142")]
            public virtual RepoItemInfo SeleccionDeTodosLosPerfilesInfo
            {
                get
                {
                    return _selecciondetodoslosperfilesInfo;
                }
            }

            /// <summary>
            /// The ChekYaEstanSeleccionados item.
            /// </summary>
            [RepositoryItem("f720249c-a563-4b89-beb9-5b2c64c20bfc")]
            public virtual Ranorex.InputTag ChekYaEstanSeleccionados
            {
                get
                {
                    return _chekyaestanseleccionadosInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ChekYaEstanSeleccionados item info.
            /// </summary>
            [RepositoryItemInfo("f720249c-a563-4b89-beb9-5b2c64c20bfc")]
            public virtual RepoItemInfo ChekYaEstanSeleccionadosInfo
            {
                get
                {
                    return _chekyaestanseleccionadosInfo;
                }
            }

            /// <summary>
            /// The Btn_CargoActual item.
            /// </summary>
            [RepositoryItem("7e6e8108-9048-496c-8889-1009268bd6be")]
            public virtual Ranorex.ButtonTag Btn_CargoActual
            {
                get
                {
                    return _btn_cargoactualInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Btn_CargoActual item info.
            /// </summary>
            [RepositoryItemInfo("7e6e8108-9048-496c-8889-1009268bd6be")]
            public virtual RepoItemInfo Btn_CargoActualInfo
            {
                get
                {
                    return _btn_cargoactualInfo;
                }
            }

            /// <summary>
            /// The Input_AnadirCargoActual item.
            /// </summary>
            [RepositoryItem("bb18b76d-3ffd-43d3-b675-fec7803ed6cb")]
            public virtual Ranorex.InputTag Input_AnadirCargoActual
            {
                get
                {
                    return _input_anadircargoactualInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Input_AnadirCargoActual item info.
            /// </summary>
            [RepositoryItemInfo("bb18b76d-3ffd-43d3-b675-fec7803ed6cb")]
            public virtual RepoItemInfo Input_AnadirCargoActualInfo
            {
                get
                {
                    return _input_anadircargoactualInfo;
                }
            }

            /// <summary>
            /// The Copy_of_GlobalTypeaheadSearchInput1 item.
            /// </summary>
            [RepositoryItem("f90bfafc-929a-4567-aa0c-fd68dd2cfc64")]
            public virtual Ranorex.InputTag Copy_of_GlobalTypeaheadSearchInput1
            {
                get
                {
                    return _copy_of_globaltypeaheadsearchinput1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_GlobalTypeaheadSearchInput1 item info.
            /// </summary>
            [RepositoryItemInfo("f90bfafc-929a-4567-aa0c-fd68dd2cfc64")]
            public virtual RepoItemInfo Copy_of_GlobalTypeaheadSearchInput1Info
            {
                get
                {
                    return _copy_of_globaltypeaheadsearchinput1Info;
                }
            }

            /// <summary>
            /// The Copy_of_GlobalTypeaheadSearchInput item.
            /// </summary>
            [RepositoryItem("04616272-ff41-4e42-9b40-5b42b2819562")]
            public virtual Ranorex.InputTag Copy_of_GlobalTypeaheadSearchInput
            {
                get
                {
                    return _copy_of_globaltypeaheadsearchinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_GlobalTypeaheadSearchInput item info.
            /// </summary>
            [RepositoryItemInfo("04616272-ff41-4e42-9b40-5b42b2819562")]
            public virtual RepoItemInfo Copy_of_GlobalTypeaheadSearchInputInfo
            {
                get
                {
                    return _copy_of_globaltypeaheadsearchinputInfo;
                }
            }

            /// <summary>
            /// The TextNombreLista item.
            /// </summary>
            [RepositoryItem("6b4a2d9f-d0a6-4e04-ac27-f396ae4c01a8")]
            public virtual Ranorex.InputTag TextNombreLista
            {
                get
                {
                    return _textnombrelistaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TextNombreLista item info.
            /// </summary>
            [RepositoryItemInfo("6b4a2d9f-d0a6-4e04-ac27-f396ae4c01a8")]
            public virtual RepoItemInfo TextNombreListaInfo
            {
                get
                {
                    return _textnombrelistaInfo;
                }
            }

            /// <summary>
            /// The ButtonGuardarNuevaLista item.
            /// </summary>
            [RepositoryItem("8a747756-4f25-497a-934a-38b5c76b1ff4")]
            public virtual Ranorex.ButtonTag ButtonGuardarNuevaLista
            {
                get
                {
                    return _buttonguardarnuevalistaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonGuardarNuevaLista item info.
            /// </summary>
            [RepositoryItemInfo("8a747756-4f25-497a-934a-38b5c76b1ff4")]
            public virtual RepoItemInfo ButtonGuardarNuevaListaInfo
            {
                get
                {
                    return _buttonguardarnuevalistaInfo;
                }
            }

            /// <summary>
            /// The Btn_BorrarCargoActual item.
            /// </summary>
            [RepositoryItem("91443328-96d9-47a7-a0c2-c6da21b53035")]
            public virtual Ranorex.Button Btn_BorrarCargoActual
            {
                get
                {
                    return _btn_borrarcargoactualInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_BorrarCargoActual item info.
            /// </summary>
            [RepositoryItemInfo("91443328-96d9-47a7-a0c2-c6da21b53035")]
            public virtual RepoItemInfo Btn_BorrarCargoActualInfo
            {
                get
                {
                    return _btn_borrarcargoactualInfo;
                }
            }

            /// <summary>
            /// The Li_CargoActual_Opcion1 item.
            /// </summary>
            [RepositoryItem("05f58acb-c028-4c77-b0fe-2ff2a9f95b84")]
            public virtual Ranorex.LiTag Li_CargoActual_Opcion1
            {
                get
                {
                    return _li_cargoactual_opcion1Info.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Li_CargoActual_Opcion1 item info.
            /// </summary>
            [RepositoryItemInfo("05f58acb-c028-4c77-b0fe-2ff2a9f95b84")]
            public virtual RepoItemInfo Li_CargoActual_Opcion1Info
            {
                get
                {
                    return _li_cargoactual_opcion1Info;
                }
            }

            /// <summary>
            /// The CrearLista item.
            /// </summary>
            [RepositoryItem("d9b67c36-5249-45cf-94b2-bc41d234616a")]
            public virtual Ranorex.SpanTag CrearLista
            {
                get
                {
                    return _crearlistaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CrearLista item info.
            /// </summary>
            [RepositoryItemInfo("d9b67c36-5249-45cf-94b2-bc41d234616a")]
            public virtual RepoItemInfo CrearListaInfo
            {
                get
                {
                    return _crearlistaInfo;
                }
            }

            /// <summary>
            /// The ArgentinaQualia item.
            /// </summary>
            [RepositoryItem("7e5c9992-1267-4564-8afb-cccc3ac60f09")]
            public virtual Ranorex.SpanTag ArgentinaQualia
            {
                get
                {
                    return _argentinaqualiaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ArgentinaQualia item info.
            /// </summary>
            [RepositoryItemInfo("7e5c9992-1267-4564-8afb-cccc3ac60f09")]
            public virtual RepoItemInfo ArgentinaQualiaInfo
            {
                get
                {
                    return _argentinaqualiaInfo;
                }
            }

            /// <summary>
            /// The FlexFullWidthJustifySpaceBetween item.
            /// </summary>
            [RepositoryItem("d53d1b7a-b983-4a65-bf43-c7b1540d784c")]
            public virtual Ranorex.DivTag FlexFullWidthJustifySpaceBetween
            {
                get
                {
                    return _flexfullwidthjustifyspacebetweenInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FlexFullWidthJustifySpaceBetween item info.
            /// </summary>
            [RepositoryItemInfo("d53d1b7a-b983-4a65-bf43-c7b1540d784c")]
            public virtual RepoItemInfo FlexFullWidthJustifySpaceBetweenInfo
            {
                get
                {
                    return _flexfullwidthjustifyspacebetweenInfo;
                }
            }

            /// <summary>
            /// The ArgentinaQualia1 item.
            /// </summary>
            [RepositoryItem("b6ace614-db43-4ff4-bb98-c5b40b1baed5")]
            public virtual Ranorex.SpanTag ArgentinaQualia1
            {
                get
                {
                    return _argentinaqualia1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ArgentinaQualia1 item info.
            /// </summary>
            [RepositoryItemInfo("b6ace614-db43-4ff4-bb98-c5b40b1baed5")]
            public virtual RepoItemInfo ArgentinaQualia1Info
            {
                get
                {
                    return _argentinaqualia1Info;
                }
            }

            /// <summary>
            /// The Copy_of_ArgentinaQualia1 item.
            /// </summary>
            [RepositoryItem("f20eb293-2228-4674-963e-3e39c52f02cd")]
            public virtual Ranorex.SpanTag Copy_of_ArgentinaQualia1
            {
                get
                {
                    return _copy_of_argentinaqualia1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_ArgentinaQualia1 item info.
            /// </summary>
            [RepositoryItemInfo("f20eb293-2228-4674-963e-3e39c52f02cd")]
            public virtual RepoItemInfo Copy_of_ArgentinaQualia1Info
            {
                get
                {
                    return _copy_of_argentinaqualia1Info;
                }
            }

            /// <summary>
            /// The MatiasGimenez item.
            /// </summary>
            [RepositoryItem("0725dc7b-dd0e-47d1-a0b6-54127ec41558")]
            public virtual Ranorex.SpanTag MatiasGimenez
            {
                get
                {
                    return _matiasgimenezInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The MatiasGimenez item info.
            /// </summary>
            [RepositoryItemInfo("0725dc7b-dd0e-47d1-a0b6-54127ec41558")]
            public virtual RepoItemInfo MatiasGimenezInfo
            {
                get
                {
                    return _matiasgimenezInfo;
                }
            }

            /// <summary>
            /// The TodosLosEmpleados item.
            /// </summary>
            [RepositoryItem("1fad1f5d-e03e-4455-b75a-15da589af9f6")]
            public virtual Ranorex.ATag TodosLosEmpleados
            {
                get
                {
                    return _todoslosempleadosInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TodosLosEmpleados item info.
            /// </summary>
            [RepositoryItemInfo("1fad1f5d-e03e-4455-b75a-15da589af9f6")]
            public virtual RepoItemInfo TodosLosEmpleadosInfo
            {
                get
                {
                    return _todoslosempleadosInfo;
                }
            }

            /// <summary>
            /// The GerenteDeEcosistemaYFidelidad item.
            /// </summary>
            [RepositoryItem("5c1e7c6d-bb1a-448d-b4d7-458a3bcd7135")]
            public virtual Ranorex.SpanTag GerenteDeEcosistemaYFidelidad
            {
                get
                {
                    return _gerentedeecosistemayfidelidadInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GerenteDeEcosistemaYFidelidad item info.
            /// </summary>
            [RepositoryItemInfo("5c1e7c6d-bb1a-448d-b4d7-458a3bcd7135")]
            public virtual RepoItemInfo GerenteDeEcosistemaYFidelidadInfo
            {
                get
                {
                    return _gerentedeecosistemayfidelidadInfo;
                }
            }

            /// <summary>
            /// The SomeSvgTag item.
            /// </summary>
            [RepositoryItem("5f93e09e-66b3-4be6-a6e6-1d51e4762777")]
            public virtual Ranorex.SvgTag SomeSvgTag
            {
                get
                {
                    return _somesvgtagInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The SomeSvgTag item info.
            /// </summary>
            [RepositoryItemInfo("5f93e09e-66b3-4be6-a6e6-1d51e4762777")]
            public virtual RepoItemInfo SomeSvgTagInfo
            {
                get
                {
                    return _somesvgtagInfo;
                }
            }

            /// <summary>
            /// The VerPerfilDeLinkedIn item.
            /// </summary>
            [RepositoryItem("c0d27101-5bf5-4ac9-aab5-192a6a64cc0f")]
            public virtual Ranorex.DivTag VerPerfilDeLinkedIn
            {
                get
                {
                    return _verperfildelinkedinInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The VerPerfilDeLinkedIn item info.
            /// </summary>
            [RepositoryItemInfo("c0d27101-5bf5-4ac9-aab5-192a6a64cc0f")]
            public virtual RepoItemInfo VerPerfilDeLinkedInInfo
            {
                get
                {
                    return _verperfildelinkedinInfo;
                }
            }

            /// <summary>
            /// The SpanTagIconPs32ck item.
            /// </summary>
            [RepositoryItem("6d462923-60f8-44f2-a0d1-a6c1e7e8da60")]
            public virtual Ranorex.SpanTag SpanTagIconPs32ck
            {
                get
                {
                    return _spantagiconps32ckInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagIconPs32ck item info.
            /// </summary>
            [RepositoryItemInfo("6d462923-60f8-44f2-a0d1-a6c1e7e8da60")]
            public virtual RepoItemInfo SpanTagIconPs32ckInfo
            {
                get
                {
                    return _spantagiconps32ckInfo;
                }
            }

            /// <summary>
            /// The DatosAObtener folder.
            /// </summary>
            [RepositoryFolder("5675ae67-f850-438a-9e38-e379467d2f4c")]
            public virtual Qualis_Bot_SalesNavigatorRepositoryFolders.DatosAObtenerFolder DatosAObtener
            {
                get { return _datosaobtener; }
            }
        }

        /// <summary>
        /// The DatosAObtenerFolder folder.
        /// </summary>
        [RepositoryFolder("5675ae67-f850-438a-9e38-e379467d2f4c")]
        public partial class DatosAObtenerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nombreInfo;

            /// <summary>
            /// Creates a new DatosAObtener  folder.
            /// </summary>
            public DatosAObtenerFolder(RepoGenBaseFolder parentFolder) :
                    base("DatosAObtener", "", parentFolder, 0, null, false, "5675ae67-f850-438a-9e38-e379467d2f4c", "")
            {
                _nombreInfo = new RepoItemInfo(this, "nombre", ".//div[#'search-results-container']//a[@innertext='Erico Behmer']", "", 30000, null, "88fa706c-6948-4715-926e-6dea7b3010e1");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5675ae67-f850-438a-9e38-e379467d2f4c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The nombre item.
            /// </summary>
            [RepositoryItem("88fa706c-6948-4715-926e-6dea7b3010e1")]
            public virtual Ranorex.ATag nombre
            {
                get
                {
                    return _nombreInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The nombre item info.
            /// </summary>
            [RepositoryItemInfo("88fa706c-6948-4715-926e-6dea7b3010e1")]
            public virtual RepoItemInfo nombreInfo
            {
                get
                {
                    return _nombreInfo;
                }
            }
        }

        /// <summary>
        /// The ContinueAndFailAppFolder folder.
        /// </summary>
        [RepositoryFolder("51ba4c9c-11a8-48ba-b3df-b0f8bcc2ce30")]
        public partial class ContinueAndFailAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pais_nombreempresaInfo;
            RepoItemInfo _buttonsiguienteInfo;
            RepoItemInfo _li_existunresultadoInfo;
            RepoItemInfo _searchresultscontainerInfo;

            /// <summary>
            /// Creates a new ContinueAndFail  folder.
            /// </summary>
            public ContinueAndFailAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContinueAndFail", "/dom[@domain='www.linkedin.com']", parentFolder, 0, null, false, "51ba4c9c-11a8-48ba-b3df-b0f8bcc2ce30", "")
            {
                _pais_nombreempresaInfo = new RepoItemInfo(this, "pais_nombreEmpresa", ".//main[#'content-main']/div[1]//ul/li[1]/div/div/div[@innertext=$pais+'_'+$nombreEmpresa]", "", 6000, null, "507a91d0-758d-405c-936c-6c3e49d887ef");
                _buttonsiguienteInfo = new RepoItemInfo(this, "ButtonSiguiente", ".//div[#'search-results-container']//button[@enabled='True']/span[@innertext='Siguiente']", "", 3000, null, "fa8ea255-1990-4c7d-9be0-7bc8903b0275");
                _li_existunresultadoInfo = new RepoItemInfo(this, "Li_ExistUnResultado", ".//div[#'search-results-container']//li[1]//span[@data-anonymize='person-name']", "", 3000, null, "278cab3a-5aca-4ab2-a8fc-8d33b34ad213");
                _searchresultscontainerInfo = new RepoItemInfo(this, "SearchResultsContainer", ".//div[#'search-results-container']", "", 5000, null, "8824ab66-2860-4f6d-b81b-bd80ebe1b481");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("51ba4c9c-11a8-48ba-b3df-b0f8bcc2ce30")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51ba4c9c-11a8-48ba-b3df-b0f8bcc2ce30")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The pais_nombreEmpresa item.
            /// </summary>
            [RepositoryItem("507a91d0-758d-405c-936c-6c3e49d887ef")]
            public virtual Ranorex.DivTag pais_nombreEmpresa
            {
                get
                {
                    return _pais_nombreempresaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The pais_nombreEmpresa item info.
            /// </summary>
            [RepositoryItemInfo("507a91d0-758d-405c-936c-6c3e49d887ef")]
            public virtual RepoItemInfo pais_nombreEmpresaInfo
            {
                get
                {
                    return _pais_nombreempresaInfo;
                }
            }

            /// <summary>
            /// The ButtonSiguiente item.
            /// </summary>
            [RepositoryItem("fa8ea255-1990-4c7d-9be0-7bc8903b0275")]
            public virtual Ranorex.SpanTag ButtonSiguiente
            {
                get
                {
                    return _buttonsiguienteInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ButtonSiguiente item info.
            /// </summary>
            [RepositoryItemInfo("fa8ea255-1990-4c7d-9be0-7bc8903b0275")]
            public virtual RepoItemInfo ButtonSiguienteInfo
            {
                get
                {
                    return _buttonsiguienteInfo;
                }
            }

            /// <summary>
            /// The Li_ExistUnResultado item.
            /// </summary>
            [RepositoryItem("278cab3a-5aca-4ab2-a8fc-8d33b34ad213")]
            public virtual Ranorex.SpanTag Li_ExistUnResultado
            {
                get
                {
                    return _li_existunresultadoInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Li_ExistUnResultado item info.
            /// </summary>
            [RepositoryItemInfo("278cab3a-5aca-4ab2-a8fc-8d33b34ad213")]
            public virtual RepoItemInfo Li_ExistUnResultadoInfo
            {
                get
                {
                    return _li_existunresultadoInfo;
                }
            }

            /// <summary>
            /// The SearchResultsContainer item.
            /// </summary>
            [RepositoryItem("8824ab66-2860-4f6d-b81b-bd80ebe1b481")]
            public virtual Ranorex.DivTag SearchResultsContainer
            {
                get
                {
                    return _searchresultscontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SearchResultsContainer item info.
            /// </summary>
            [RepositoryItemInfo("8824ab66-2860-4f6d-b81b-bd80ebe1b481")]
            public virtual RepoItemInfo SearchResultsContainerInfo
            {
                get
                {
                    return _searchresultscontainerInfo;
                }
            }
        }

        /// <summary>
        /// The OutputEmpresasXlsxExcelAppFolder folder.
        /// </summary>
        [RepositoryFolder("041cc2f3-9051-467d-80af-d1124ff1688d")]
        public partial class OutputEmpresasXlsxExcelAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabdataInfo;
            RepoItemInfo _removeduplicatesInfo;
            RepoItemInfo _unselectallInfo;
            RepoItemInfo _nombrecompletoInfo;
            RepoItemInfo _button_nameokInfo;
            RepoItemInfo _button_textokInfo;

            /// <summary>
            /// Creates a new OutputEmpresasXlsxExcel  folder.
            /// </summary>
            public OutputEmpresasXlsxExcelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OutputEmpresasXlsxExcel", "/form[@processname='EXCEL']", parentFolder, 30000, null, true, "041cc2f3-9051-467d-80af-d1124ff1688d", "")
            {
                _tabdataInfo = new RepoItemInfo(this, "TabData", ".//tabpage[@automationid='TabData']", "", 30000, null, "6a77f4d5-6fb1-41c9-8d87-92ce78a1f27e");
                _removeduplicatesInfo = new RepoItemInfo(this, "RemoveDuplicates", ".//button[@automationid='RemoveDuplicates']", "", 30000, null, "9b23601b-506e-4c41-845e-55e48cba4df7");
                _unselectallInfo = new RepoItemInfo(this, "UnselectAll", ".//container[@controlname='Remove Duplicates']//button[@name='Unselect All']", "", 30000, null, "86a977ad-9ae8-47ba-8277-427749106522");
                _nombrecompletoInfo = new RepoItemInfo(this, "NombreCompleto", ".//container[@controlname='Remove Duplicates']//checkbox[@name='Nombre Completo']", "", 30000, null, "03547421-a84f-4dfd-b381-0413facf7190");
                _button_nameokInfo = new RepoItemInfo(this, "Button_NameOK", ".//container[@controlname='Remove Duplicates']//button[@name='OK']", "", 30000, null, "2a370f4a-c73c-49bb-8103-ad03db14fb01");
                _button_textokInfo = new RepoItemInfo(this, "Button_TextOK", "button[@text='OK']", "", 30000, null, "d7359b6d-3a88-4d7b-9546-68b054ad8ae5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("041cc2f3-9051-467d-80af-d1124ff1688d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("041cc2f3-9051-467d-80af-d1124ff1688d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TabData item.
            /// </summary>
            [RepositoryItem("6a77f4d5-6fb1-41c9-8d87-92ce78a1f27e")]
            public virtual Ranorex.TabPage TabData
            {
                get
                {
                    return _tabdataInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TabData item info.
            /// </summary>
            [RepositoryItemInfo("6a77f4d5-6fb1-41c9-8d87-92ce78a1f27e")]
            public virtual RepoItemInfo TabDataInfo
            {
                get
                {
                    return _tabdataInfo;
                }
            }

            /// <summary>
            /// The RemoveDuplicates item.
            /// </summary>
            [RepositoryItem("9b23601b-506e-4c41-845e-55e48cba4df7")]
            public virtual Ranorex.Button RemoveDuplicates
            {
                get
                {
                    return _removeduplicatesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RemoveDuplicates item info.
            /// </summary>
            [RepositoryItemInfo("9b23601b-506e-4c41-845e-55e48cba4df7")]
            public virtual RepoItemInfo RemoveDuplicatesInfo
            {
                get
                {
                    return _removeduplicatesInfo;
                }
            }

            /// <summary>
            /// The UnselectAll item.
            /// </summary>
            [RepositoryItem("86a977ad-9ae8-47ba-8277-427749106522")]
            public virtual Ranorex.Button UnselectAll
            {
                get
                {
                    return _unselectallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UnselectAll item info.
            /// </summary>
            [RepositoryItemInfo("86a977ad-9ae8-47ba-8277-427749106522")]
            public virtual RepoItemInfo UnselectAllInfo
            {
                get
                {
                    return _unselectallInfo;
                }
            }

            /// <summary>
            /// The NombreCompleto item.
            /// </summary>
            [RepositoryItem("03547421-a84f-4dfd-b381-0413facf7190")]
            public virtual Ranorex.CheckBox NombreCompleto
            {
                get
                {
                    return _nombrecompletoInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The NombreCompleto item info.
            /// </summary>
            [RepositoryItemInfo("03547421-a84f-4dfd-b381-0413facf7190")]
            public virtual RepoItemInfo NombreCompletoInfo
            {
                get
                {
                    return _nombrecompletoInfo;
                }
            }

            /// <summary>
            /// The Button_NameOK item.
            /// </summary>
            [RepositoryItem("2a370f4a-c73c-49bb-8103-ad03db14fb01")]
            public virtual Ranorex.Button Button_NameOK
            {
                get
                {
                    return _button_nameokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_NameOK item info.
            /// </summary>
            [RepositoryItemInfo("2a370f4a-c73c-49bb-8103-ad03db14fb01")]
            public virtual RepoItemInfo Button_NameOKInfo
            {
                get
                {
                    return _button_nameokInfo;
                }
            }

            /// <summary>
            /// The Button_TextOK item.
            /// </summary>
            [RepositoryItem("d7359b6d-3a88-4d7b-9546-68b054ad8ae5")]
            public virtual Ranorex.Button Button_TextOK
            {
                get
                {
                    return _button_textokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_TextOK item info.
            /// </summary>
            [RepositoryItemInfo("d7359b6d-3a88-4d7b-9546-68b054ad8ae5")]
            public virtual RepoItemInfo Button_TextOKInfo
            {
                get
                {
                    return _button_textokInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("6f3b421b-86e1-4ef2-bbc7-d7ddfe587996")]
        public partial class ChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _salesqlbrowserextensionbuttonInfo;

            /// <summary>
            /// Creates a new Chrome  folder.
            /// </summary>
            public ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome", "/form[@processname='chrome']", parentFolder, 30000, null, true, "6f3b421b-86e1-4ef2-bbc7-d7ddfe587996", "")
            {
                _salesqlbrowserextensionbuttonInfo = new RepoItemInfo(this, "SalesQLBrowserExtensionButton", ".//button[@accessiblename>'SalesQL Browser Extension']", "", 30000, null, "b74bdfe0-6def-4c1d-8faf-58e631b4e180");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6f3b421b-86e1-4ef2-bbc7-d7ddfe587996")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6f3b421b-86e1-4ef2-bbc7-d7ddfe587996")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SalesQLBrowserExtensionButton item.
            /// </summary>
            [RepositoryItem("b74bdfe0-6def-4c1d-8faf-58e631b4e180")]
            public virtual Ranorex.Button SalesQLBrowserExtensionButton
            {
                get
                {
                    return _salesqlbrowserextensionbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SalesQLBrowserExtensionButton item info.
            /// </summary>
            [RepositoryItemInfo("b74bdfe0-6def-4c1d-8faf-58e631b4e180")]
            public virtual RepoItemInfo SalesQLBrowserExtensionButtonInfo
            {
                get
                {
                    return _salesqlbrowserextensionbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ContAndFail_ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("29d6aa49-1a0a-40e2-9254-b03910dce2bf")]
        public partial class ContAndFail_ChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _obtenerphonenewInfo;
            RepoItemInfo _obteneremailnewInfo;
            RepoItemInfo _obtenerdatosbuttonInfo;
            RepoItemInfo _nextbuttonInfo;

            /// <summary>
            /// Creates a new ContAndFail_Chrome  folder.
            /// </summary>
            public ContAndFail_ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContAndFail_Chrome", "/form[@processname='chrome']", parentFolder, 0, null, false, "29d6aa49-1a0a-40e2-9254-b03910dce2bf", "")
            {
                _obtenerphonenewInfo = new RepoItemInfo(this, "ObtenerPhoneNew", ".//container[@accessiblename='SalesQL']//text[@accessiblename~'\\+' and @accessiblename~'[0-9]'][$index]", "", 10000, null, "1719f219-17d8-4d14-b691-985db7e00005");
                _obteneremailnewInfo = new RepoItemInfo(this, "ObtenerEmailNew", ".//container[@accessiblename='SalesQL']//text[@accessiblename~'@' and @accessiblename~'.'][$index]", "", 10000, null, "37fe0e26-1529-4081-b805-65ee7e919a9d");
                _obtenerdatosbuttonInfo = new RepoItemInfo(this, "ObtenerDatosButton", ".//container[@accessiblename='SalesQL']//text[@accessiblename='add']", "", 10000, null, "5104c1b5-d0b6-40c0-a47f-4aa1b80b1a2f");
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", ".//container[@accessiblename='SalesQL']//text[@accessiblename='chevron_right']", "", 10000, null, "4a50e875-3ff4-43bb-aa45-ebc9b67794e0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("29d6aa49-1a0a-40e2-9254-b03910dce2bf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("29d6aa49-1a0a-40e2-9254-b03910dce2bf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ObtenerPhoneNew item.
            /// </summary>
            [RepositoryItem("1719f219-17d8-4d14-b691-985db7e00005")]
            public virtual Ranorex.Text ObtenerPhoneNew
            {
                get
                {
                    return _obtenerphonenewInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ObtenerPhoneNew item info.
            /// </summary>
            [RepositoryItemInfo("1719f219-17d8-4d14-b691-985db7e00005")]
            public virtual RepoItemInfo ObtenerPhoneNewInfo
            {
                get
                {
                    return _obtenerphonenewInfo;
                }
            }

            /// <summary>
            /// The ObtenerEmailNew item.
            /// </summary>
            [RepositoryItem("37fe0e26-1529-4081-b805-65ee7e919a9d")]
            public virtual Ranorex.Text ObtenerEmailNew
            {
                get
                {
                    return _obteneremailnewInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ObtenerEmailNew item info.
            /// </summary>
            [RepositoryItemInfo("37fe0e26-1529-4081-b805-65ee7e919a9d")]
            public virtual RepoItemInfo ObtenerEmailNewInfo
            {
                get
                {
                    return _obteneremailnewInfo;
                }
            }

            /// <summary>
            /// The ObtenerDatosButton item.
            /// </summary>
            [RepositoryItem("5104c1b5-d0b6-40c0-a47f-4aa1b80b1a2f")]
            public virtual Ranorex.Text ObtenerDatosButton
            {
                get
                {
                    return _obtenerdatosbuttonInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ObtenerDatosButton item info.
            /// </summary>
            [RepositoryItemInfo("5104c1b5-d0b6-40c0-a47f-4aa1b80b1a2f")]
            public virtual RepoItemInfo ObtenerDatosButtonInfo
            {
                get
                {
                    return _obtenerdatosbuttonInfo;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("4a50e875-3ff4-43bb-aa45-ebc9b67794e0")]
            public virtual Ranorex.Text NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("4a50e875-3ff4-43bb-aa45-ebc9b67794e0")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The InicioAppFolder folder.
        /// </summary>
        [RepositoryFolder("d8d97ac7-149e-4d30-aced-65122ba5e54c")]
        public partial class InicioAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Inicio  folder.
            /// </summary>
            public InicioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Inicio", "/winapp[@packagename='Microsoft.Windows.StartMenuExperienceHost']", parentFolder, 30000, null, true, "d8d97ac7-149e-4d30-aced-65122ba5e54c", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d8d97ac7-149e-4d30-aced-65122ba5e54c")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d8d97ac7-149e-4d30-aced-65122ba5e54c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
