///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RemoverDuplicados recording.
    /// </summary>
    [TestModule("25f676b1-8a2c-402e-8ca8-618ccc799ac3", ModuleType.Recording, 1)]
    public partial class RemoverDuplicados : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Qualis_Bot_SalesNavigatorRepository repository.
        /// </summary>
        public static Qualis_Bot_SalesNavigatorRepository repo = Qualis_Bot_SalesNavigatorRepository.Instance;

        static RemoverDuplicados instance = new RemoverDuplicados();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RemoverDuplicados()
        {
            IdExel = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RemoverDuplicados Instance
        {
            get { return instance; }
        }

#region Variables

        string _IdExel;

        /// <summary>
        /// Gets or sets the value of variable IdExel.
        /// </summary>
        [TestVariable("21772a8e-34af-4d18-a2b3-0d176b943db3")]
        public string IdExel
        {
            get { return _IdExel; }
            set { _IdExel = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\TEMP\\OutputEmpresas.xlsx' in normal mode. Return value bound to $IdExel.", new RecordItemIndex(0));
            IdExel = ValueConverter.ToString(Host.Local.RunApplication("C:\\TEMP\\OutputEmpresas.xlsx", "", "C:\\TEMP", false));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OutputEmpresasXlsxExcel.TabData' at Center.", repo.OutputEmpresasXlsxExcel.TabDataInfo, new RecordItemIndex(1));
            repo.OutputEmpresasXlsxExcel.TabData.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OutputEmpresasXlsxExcel.RemoveDuplicates' at Center.", repo.OutputEmpresasXlsxExcel.RemoveDuplicatesInfo, new RecordItemIndex(2));
            repo.OutputEmpresasXlsxExcel.RemoveDuplicates.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OutputEmpresasXlsxExcel.UnselectAll' at Center.", repo.OutputEmpresasXlsxExcel.UnselectAllInfo, new RecordItemIndex(3));
            repo.OutputEmpresasXlsxExcel.UnselectAll.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Check() on item 'OutputEmpresasXlsxExcel.NombreCompleto'.", repo.OutputEmpresasXlsxExcel.NombreCompletoInfo, new RecordItemIndex(4));
            repo.OutputEmpresasXlsxExcel.NombreCompleto.Check();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OutputEmpresasXlsxExcel.Button_NameOK' at Center.", repo.OutputEmpresasXlsxExcel.Button_NameOKInfo, new RecordItemIndex(5));
            repo.OutputEmpresasXlsxExcel.Button_NameOK.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OutputEmpresasXlsxExcel.Button_TextOK' at Center.", repo.OutputEmpresasXlsxExcel.Button_TextOKInfo, new RecordItemIndex(7));
            repo.OutputEmpresasXlsxExcel.Button_TextOK.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Skey}{LControlKey up}'.", new RecordItemIndex(8));
            Keyboard.Press("{LControlKey down}{Skey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'OutputEmpresasXlsxExcel'.", repo.OutputEmpresasXlsxExcel.SelfInfo, new RecordItemIndex(9));
            Host.Current.KillApplication(repo.OutputEmpresasXlsxExcel.Self);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
