///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Qualis_Bot_SalesNavigator
{
	public partial class ValidacionEmpresaEIndustria2
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void validacionEmpresa(string nombreEmpresa)
		{
			{

				// Definir la variable global nombreEmpresa
				//string nombreEmpresa = "";

				// Verificar si la variable nombreEmpresa tiene un valor
				//if (!string.IsNullOrEmpty(encontroEmpresa))
				/*if (Validate.Exists(repo.InicioSalesNavigator.ValidacionNombreEmpresaIndustriaInfo, null, false))
				{
					// Aquí entra si la variable nombreEmpresa tiene un valor (true)
					Report.Info($"El nombre de la empresa es: {encontroEmpresa}");
					// Establecer condición como verdadera (true)
					//bool condicion = true;
					TestSuite.CurrentTestContainer.Parameters["encontroEmpresa"] = "True";
					//TestSuite.Current.Parameters["encontroEmpresa"] = "True";
					Report.Info("El valor del parametro encontroEmpresa es: " + TestSuite.CurrentTestContainer.Parameters["encontroEmpresa"]);
				}
				else
				{
					// Aquí entra si la variable nombreEmpresa está vacía o es nula (false)
					Report.Info("La variable empresa está vacía o es nula.");
					// Establecer condición como falsa (false)
					//bool condicion = false;
					TestSuite.Current.Parameters["encontroEmpresa"] = "False";
//				}*/
			}
//
	}

}
}
