///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Qualis_Bot_SalesNavigator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidacionEmpresaEIndustria recording.
    /// </summary>
    [TestModule("c167697a-3c37-4cbf-a1cf-93f7b333bd9b", ModuleType.Recording, 1)]
    public partial class ValidacionEmpresaEIndustria : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Qualis_Bot_SalesNavigatorRepository repository.
        /// </summary>
        public static Qualis_Bot_SalesNavigatorRepository repo = Qualis_Bot_SalesNavigatorRepository.Instance;

        static ValidacionEmpresaEIndustria instance = new ValidacionEmpresaEIndustria();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidacionEmpresaEIndustria()
        {
            nombreEmpresa = "Banco Galicia";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidacionEmpresaEIndustria Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable nombreEmpresa.
        /// </summary>
        [TestVariable("243376d0-5738-43b5-a836-b6324bd9751e")]
        public string nombreEmpresa
        {
            get { return repo.nombreEmpresa; }
            set { repo.nombreEmpresa = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Industria.
        /// </summary>
        [TestVariable("48ee2248-30c5-4ed5-82d6-ec3f16680e3a")]
        public string Industria
        {
            get { return repo.Industria; }
            set { repo.Industria = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'InicioSalesNavigator.ValidacionNombreEmpresaIndustria'.", repo.InicioSalesNavigator.ValidacionNombreEmpresaIndustriaInfo, new RecordItemIndex(0));
                //Validate.Exists(repo.InicioSalesNavigator.ValidacionNombreEmpresaIndustriaInfo, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            //Report.Screenshot(ReportLevel.Info, "User", "", repo.InicioSalesNavigator.ImgValidacionNombreEmpresaIndustria, false, new RecordItemIndex(1));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InicioSalesNavigator.ValidacionNombreEmpresaIndustria' at Center.", repo.InicioSalesNavigator.ValidacionNombreEmpresaIndustriaInfo, new RecordItemIndex(2));
            //repo.InicioSalesNavigator.ValidacionNombreEmpresaIndustria.Click();
            //Delay.Milliseconds(0);
            
            validacionEmpresa(nombreEmpresa);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
